name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build JAR
      run: ./gradlew clean build

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bank:latest .

    - name: DockerHub Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/bank:latest

    - name: Copy JAR to Cloud
      run: |
        echo "${{ secrets.CLOUD_KEY }}" > cloud_key.pem
        chmod 600 cloud_key.pem
        scp -o StrictHostKeyChecking=no -i cloud_key.pem build/libs/*.jar ${{ secrets.CLOUD_HOST }}:${{ secrets.REMOTE_PATH }}
